name: Update ChangeLog on Release Branch Creation

on:
  create:
    branches:
      - release/QA-*

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Fetch develop branch
      run: |
        git fetch origin develop:develop

    - name: Get new commits from develop
      run: |
        git log origin/develop -n 10 --oneline > new_commits.txt

    - name: Update CHANGELOG.md
      run: |
        echo "## Release $(date +'%Y-%m-%d')" >> CHANGELOG.md
        cat new_commits.txt >> CHANGELOG.md
        echo "" >> CHANGELOG.md

    - name: Commit changes
      run: |
        git add CHANGELOG.md
        git commit -m "Update CHANGELOG.md for ${{ github.ref_name }}"

    - name: Push CHANGELOG.md to release
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref_name }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
